[33mcommit 9c490887cef3d84d93e2a901c2e9bc75bec33b8b[m[33m ([m[1;36mHEAD[m[33m)[m
Author: Your Name <you@example.com>
Date:   Sun Oct 5 10:51:37 2025 -0500

    Website is working - updated the marketing page

 template/app/blog/astro.config.mjs                 |  30 [31m----[m
 .../app/blog/postmarkr-canvas-co-57397-main.zip    | Bin [31m0[m -> [32m324274[m bytes
 ...s-co-57397-main.zip\357\200\272Zone.Identifier" | Bin [31m0[m -> [32m185[m bytes
 template/app/blog/src/components/MyHeader.astro    | 161 [32m++++++++++[m[31m-------[m
 template/app/main.wasp                             |  39 [32m++[m[31m--[m
 template/app/public/sitemap.xml                    |   6 [32m+[m[31m-[m
 template/app/schema.prisma                         |   2 [32m+[m[31m-[m
 .../admin/dashboards/settings/AppSettingsPage.tsx  |   3 [31m-[m
 template/app/src/admin/layout/DefaultLayout.tsx    |  16 [32m+[m[31m-[m
 template/app/src/admin/operations.ts               |   1 [31m-[m
 template/app/src/auth/userSignupFields.ts          |  14 [31m--[m
 template/app/src/beta/UpgradeAccessPage.tsx        | 107 [31m-----------[m
 template/app/src/beta/accessHelpers.ts             |  75 [31m--------[m
 template/app/src/beta/operations.ts                |  78 [31m--------[m
 template/app/src/client/App.tsx                    |  44 [32m+++[m[31m--[m
 template/app/src/client/Main.css                   | 100 [32m+++++++[m[31m----[m
 .../app/src/client/components/NavBar/NavBar.tsx    |   6 [32m+[m[31m-[m
 .../app/src/client/components/NavBar/constants.ts  |   9 [32m+[m
 template/app/src/demo-ai-app/DemoAppPage.tsx       |  15 [31m--[m
 template/app/src/landing-page/LandingPage.tsx      |  87 [32m++[m[31m-------[m
 template/app/src/landing-page/components/FAQ.tsx   | 109 [32m++++++++[m[31m----[m
 .../src/landing-page/components/FeaturesGrid.tsx   | 196 [32m+++++++++[m[31m------------[m
 template/app/src/landing-page/components/Hero.tsx  | 134 [32m++++++[m[31m--------[m
 .../app/src/landing-page/components/HowItWorks.tsx |  81 [32m+++++++++[m
 .../app/src/landing-page/components/Pricing.tsx    | 140 [32m+++++++++++++++[m
 .../src/landing-page/components/Testimonials.tsx   | 139 [32m++++++++[m[31m-------[m
 template/app/src/landing-page/contentSections.ts   |  13 [32m+[m[31m-[m
 template/app/src/legal/PrivacyPolicyPage.tsx       |  91 [32m++++++++++[m
 template/app/src/legal/TermsOfServicePage.tsx      | 125 [32m+++++++++++++[m
 template/app/src/mail/operations.ts                |  14 [32m+[m[31m-[m
 template/app/src/server/scripts/dbSeeds.ts         |   7 [32m+[m[31m-[m
 template/app/src/server/sitemap.ts                 |  24 [32m+++[m
 template/app/src/shared/accessHelpers.ts           |  12 [32m++[m
 template/app/src/shared/appSettings.ts             |  20 [31m---[m
 .../app/src/test/critical/mail-operations.test.ts  |  19 [31m--[m
 template/app/src/test/setup.ts                     |   1 [31m-[m
 template/app/src/test/utils/factories.ts           |   9 [32m+[m[31m-[m
 template/app/src/test/utils/mocks.ts               |   2 [32m+[m[31m-[m
 template/app/src/user/AccountPage.tsx              |   2 [32m+[m[31m-[m
 template/app/tailwind.config.js                    |  52 [32m++++++[m
 40 files changed, 1087 insertions(+), 896 deletions(-)
