import React from 'react';
import { ExternalLink, FileText, Package } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '../../components/ui/card';
import { Alert, AlertDescription } from '../../components/ui/alert';
import { parseLobThumbnails, type MailPreviewProps } from '../types';

/**
 * Component to display mail piece previews from Lob
 * 
 * Shows:
 * - Thumbnail images generated by Lob
 * - Direct link to view full preview in Lob
 * - Fallback messaging when previews aren't available yet
 */
export function MailPreview({ 
  thumbnails, 
  lobPreviewUrl, 
  mailType = 'mail',
  lobId,
  className = '' 
}: MailPreviewProps) {
  // Parse thumbnails using the utility function
  const thumbnailArray: string[] = React.useMemo(() => {
    return parseLobThumbnails(thumbnails);
  }, [thumbnails]);

  // Show loading state if mail is submitted but no previews yet
  if (lobId && thumbnailArray.length === 0) {
    return (
      <Card className={className}>
        <CardHeader>
          <CardTitle className="flex items-center text-base">
            <Package className="h-5 w-5 mr-2" />
            Mail Preview
          </CardTitle>
        </CardHeader>
        <CardContent>
          <Alert>
            <FileText className="h-4 w-4" />
            <AlertDescription>
              Your {mailType} has been submitted to Lob. Preview images will be available shortly.
              {lobPreviewUrl && (
                <>
                  {' '}In the meantime, you can{' '}
                  <a 
                    href={lobPreviewUrl} 
                    target="_blank" 
                    rel="noopener noreferrer"
                    className="text-blue-600 hover:underline inline-flex items-center"
                  >
                    view it in Lob <ExternalLink className="h-3 w-3 ml-1" />
                  </a>
                </>
              )}
            </AlertDescription>
          </Alert>
        </CardContent>
      </Card>
    );
  }

  // Don't show component if no previews and not submitted
  if (!lobId && thumbnailArray.length === 0) {
    return null;
  }

  return (
    <Card className={className}>
      <CardHeader>
        <CardTitle className="flex items-center justify-between text-base">
          <span className="flex items-center">
            <FileText className="h-5 w-5 mr-2" />
            Mail Preview
          </span>
          {lobPreviewUrl && (
            <a 
              href={lobPreviewUrl} 
              target="_blank" 
              rel="noopener noreferrer"
              className="text-sm font-normal text-blue-600 hover:underline flex items-center"
            >
              View Full Preview <ExternalLink className="h-3 w-3 ml-1" />
            </a>
          )}
        </CardTitle>
      </CardHeader>
      <CardContent>
        {thumbnailArray.length > 0 ? (
          <div className="space-y-4">
            <p className="text-sm text-gray-600">
              Preview of your {mailType} as generated by Lob. This is what your recipient will receive.
            </p>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {thumbnailArray.map((url, idx) => (
                <div 
                  key={idx} 
                  className="relative group overflow-hidden rounded-lg border border-gray-200 shadow-sm hover:shadow-md transition-shadow"
                >
                  <img 
                    src={url} 
                    alt={`${mailType} preview - Page ${idx + 1}`}
                    className="w-full h-auto object-contain bg-white"
                    loading="lazy"
                    onError={(e) => {
                      // Hide broken images
                      (e.target as HTMLImageElement).style.display = 'none';
                    }}
                  />
                  <div className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/50 to-transparent p-2">
                    <span className="text-white text-xs font-medium">
                      Page {idx + 1}
                    </span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        ) : (
          <Alert>
            <FileText className="h-4 w-4" />
            <AlertDescription>
              No preview images available yet. They will appear once Lob processes your mail piece.
            </AlertDescription>
          </Alert>
        )}
      </CardContent>
    </Card>
  );
}

