import { HttpError } from 'wasp/server';
import type { ResendVerificationEmail } from 'wasp/server/operations';
import { sendWelcomeEmail } from '../server/email/mailNotifications';

// Type will be auto-generated by Wasp based on main.wasp definition
export const sendWelcomeEmailAction = async (args: void, context: any): Promise<{ success: boolean }> => {
  if (!context.user) {
    throw new HttpError(401, 'Not authorized');
  }

  try {
    // Get user email
    const userEmail = context.user.identities?.email?.email || context.user.email;
    const userName = context.user.username || userEmail?.split('@')[0] || 'Valued Customer';
    
    if (!userEmail) {
      console.error('Cannot send welcome email: user email not found', {
        userId: context.user.id
      });
      return { success: false };
    }

    await sendWelcomeEmail(userEmail, userName);
    
    return { success: true };
  } catch (error) {
    console.error('Failed to send welcome email:', error);
    // Don't throw - email failure shouldn't block user flow
    return { success: false };
  }
};

export const resendVerificationEmail: ResendVerificationEmail<void, { success: boolean; message: string }> = async (args, context) => {
  if (!context.user) {
    throw new HttpError(401, 'Not authorized');
  }

  // Check if user already has a verified email
  const userEmail = context.user.email;
  const isEmailVerified = !!userEmail;
  
  if (isEmailVerified) {
    return { 
      success: false, 
      message: 'Your email is already verified. You can proceed to login.' 
    };
  }

  // Since Wasp handles email verification internally and we don't have direct access
  // to regenerate verification tokens, we'll provide helpful guidance to users
  return {
    success: true,
    message: 'Please check your spam/junk folder for the original verification email. If you still can\'t find it, try signing up again or contact support at nathan@postmarkr.com for assistance.'
  };
};
