import { HttpError } from 'wasp/server';
import type { ResendVerificationEmail } from 'wasp/server/operations';
import { sendWelcomeEmail } from '../server/email/mailNotifications';

// Type will be auto-generated by Wasp based on main.wasp definition
export const sendWelcomeEmailAction = async (args: void, context: any): Promise<{ success: boolean }> => {
  if (!context.user) {
    throw new HttpError(401, 'Not authorized');
  }

  try {
    // Get user email
    const userEmail = context.user.identities?.email?.email || context.user.email;
    const userName = context.user.username || userEmail?.split('@')[0] || 'Valued Customer';
    
    if (!userEmail) {
      console.error('Cannot send welcome email: user email not found', {
        userId: context.user.id
      });
      return { success: false };
    }

    await sendWelcomeEmail(userEmail, userName);
    
    return { success: true };
  } catch (error) {
    console.error('Failed to send welcome email:', error);
    // Don't throw - email failure shouldn't block user flow
    return { success: false };
  }
};

export const resendVerificationEmail: ResendVerificationEmail<void, { success: boolean; message: string }> = async (args, context) => {
  // Note: Since we cannot directly access the user without authentication,
  // and users needing verification aren't authenticated yet, we provide
  // helpful guidance instead of actual resending functionality
  
  // Check if user is authenticated (they shouldn't be if they need verification)
  if (context.user) {
    // Check if user's email is already verified via identities
    const emailIdentity = context.user.identities?.email;
    const isEmailVerified = emailIdentity?.isEmailVerified ?? false;
    
    if (isEmailVerified) {
      return { 
        success: false, 
        message: 'Your email is already verified. You can proceed to login.' 
      };
    }
  }

  // Provide helpful guidance for users who can't find their verification email
  return {
    success: true,
    message: 'Please check your spam/junk folder for the verification email. If you still can\'t find it within a few minutes, try signing up again with the same email address to receive a new verification link, or contact support at nathan@postmarkr.com for assistance.'
  };
};
