# fly.toml app configuration file generated for postmarkr-server on 2025-10-01T09:06:56-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'postmarkr-server-server'
primary_region = 'ord'

[build]

[env]
  PORT = "8080"
  NODE_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  # Health check configuration
  [[http_service.checks]]
    grace_period = "60s"  # Increased grace period for startup validation
    interval = "15s"
    method = "GET"
    timeout = "10s"
    path = "/health/simple"
    
    [http_service.checks.headers]
      User-Agent = "Fly-Health-Check"

  # Additional comprehensive health check
  [[http_service.checks]]
    grace_period = "90s"  # Longer grace period for comprehensive checks
    interval = "30s"
    method = "GET"
    timeout = "15s"
    path = "/health"  # Full health check endpoint
    
    [http_service.checks.headers]
      User-Agent = "Fly-Health-Check"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

# Metrics configuration for monitoring
# Port 9091 is the standard Fly.io metrics port for Prometheus scraping
[metrics]
  port = 9091
  path = "/metrics"
